### PR TITLE
refactor and simplify configuration loading

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by 515k4** [comment]
I did some testing of released 4.0.1 and version with this merge and they do not behave the same. Moreover, in both cases, they could read your `~/.flake8`. Consider this example:

```
# Test setup
~$ echo -e "[flake8]\nmax-line-length = 88" > ~/.flake8
~$ mkdir project1 project2 project3
~$ echo 'print("This is very long line. This is very long line. This is very long line. End")' > project1/example.py
~$ cp project1/example.py project2
~$ cp project1/example.py project3
~$ touch project2/setup.cfg
~$ echo "[flake8]" > project3/setup.cfg
```

```
# Run with 4.0.1
~/project1$ flake8 example.py
~/project1$ cd ../project2
~/project2$ flake8 example.py
E501 line too long (84 > 79 characters)
~/project2$ cd ../project3
~/project3$ flake8 example.py
E501 line too long (84 > 79 characters)
```

```
# Run with freshly cloned repo (7a02d04)
~/project1$ flake8 example.py
~/project1$ cd ../project2
~/project2$ flake8 example.py
~/project2$ cd ../project3
~/project3$ flake8 example.py
example.py:1:80: E501 line too long (84 > 79 characters)
```

The documentation says: the configuration is in your project in one of `setup.cfg`, `tox.ini`, or `.flake8` (It doesn't say in this order but the order is also important). In 4.0.1 the project's directory is a directory with any of those files regarding its content. After refactoring, project's directory means some of those files must have `[flake8]` section. In any case, if no directory seems to be project's directory, it can accidently parse your ~/.flake8, which I understand it should not parse anymore.

I am fine with both of  those behaviors but I really suggest either more verbose documentation or flake8 itself. Now it is quite confusing and when I run flake8 on very simple files without project (like example or testing files) I get unexpected results.

**Comment by asottile** [comment]
yes, this fixes a bug in the current versions where a configuration without `[flake8]` is considered a flake8 configuration

**Comment by asottile** [comment]
specifically #199

**Comment by 515k4** [comment]
Good! But if that was a bug and I am not really using `[flake8]` in any of my `setup.cfg` nor `tox.ini`, my `~/.flake8` will continue to work. Is this intended?

**Comment by asottile** [comment]
it's not supported but it may work by accident -- I would not rely on that behaviour

**Comment by 515k4** [comment]
I fear this is not the type of accident you want have in such a pedantic tool. You state in 4.0.0 changelog that _files will not be searched for in the user’s home directory (e.g., ~/.flake8)_ and suddenly the tool is searching exactly for that file because it's unclear what qualifies a directory to be a projects's directory.

Please consider adding a warning when using `~/.flake8` to not rely on it  and also consider updating the documentation. The file order and what is project directory exactly.

**Comment by asottile** [comment]
I don't appreciate the attitude

**Pull request merged**
