### PR TITLE
pregenerate the pycodestyle plugin to avoid call overhead

### PR DESCRIPTION
**Pull request by asottile**
this saves 10-12% off the execution time of `flake8 -j1 src/`

- best of 10 before: 1.469s
- best of 10 after: 1.301s

the implementation is a tiny bit fragile, though not exceedingly so as we pin `pycodestyle`.

### CODE REVIEW

**Comment by andersk** [comment]
Would it be even better to generate that code and `exec()` it at runtime? That could give you a way to remove the overhead for deselected plugins (#751).

**Comment by asottile** [comment]
> Would it be even better to generate that code and `exec()` it at runtime? That could give you a way to remove the overhead for deselected plugins (#751).

#751 is basically impossible without refactoring how pycodestyle works (checks in pycodestyle do not all fall under unique prefixes and criss cross over)

the codegen is also relatively slow so doing it at runtime would eliminate most of the performance gain

**Review by sigmavirus24 — APPROVED** [review]
I'm never really a fan of code generation but the improvement is hard to deny. I _suspect_ most of the speed comes from fewer `entry_points` given how abysmal that's always been (regardless of how much faster `importlib` is than `setuptools`/`pkg_resources`).

**Comment by asottile** [comment]
surprisingly, most of the speedup comes from not needing to call `keywords_for`  and building small kwargs dictionaries many many times

**Pull request merged**
