### PR TITLE
Require mock 2.0.0, because unit tests are failing on older one

### PR DESCRIPTION
**Pull request by onovy**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Where are you getting an older version of mock?

**Comment by onovy** [comment]
for example in Debian Jessie is mock 1.0.1

**Comment by sigmavirus24** [comment]
Please update https://github.com/PyCQA/flake8/blob/a981fe34ed5d02c762e40e1ed2d6f309290035b3/tox.ini#L7 too. I understand downstream packagers don't care about tox.ini but there's no need for the two to be out of sync.

**Comment by onovy** [comment]
right, fixed

**Comment by sigmavirus24** [comment]
Thanks @onovy!

**Comment by onovy** [comment]
Thanks too

**Pull request merged**
