### PR TITLE
Replace for loop with list comprehension

### PR DESCRIPTION
**Pull request by monosans**

### CODE REVIEW

**Comment by asottile** [comment]
@monosans please stop

**Comment by monosans** [comment]
Hey @asottile! Why wasn't this one merged?

**Comment by asottile** [comment]
the same reason the others are closed, we do not accept cosmetic changes

**Comment by monosans** [comment]
> cosmetic changes

@asottile so you think there's no performance benefit from using the list comprehension instead of .append()?

**Comment by asottile** [comment]
show it's significant in macro benchmarks of flake8 and I'll consider it

**Pull request closed without merging**
