### PR TITLE
Add debug printout when reading config file

### PR DESCRIPTION
**Pull request by fwinkl**
Add a debug printout when reading the (extra) config files(s). A similar line was available in version 3.x before the removal of the user-specific config file parsing.

### CODE REVIEW

**Comment by asottile** [comment]
sorry, I'm planning on slowly phasing out debug lines -- use the debugger if you need it

**Comment by fwinkl** [comment]
@asottile, I think there is trade-off to be made between debug messages for "debugging" by developers (i.e. if they have a performance impact) and providing additional information to the user. Especially for projects with multiple sub-directories, possibly using different flake8 configurations, having such an "informational" message can be extremely helpful in trying to understand which configuration file is being used.

The same is true by the way for the current DEBUG message on which error codes are selected/ignored. I hope you are not planning to remove those either.

**Comment by asottile** [comment]
debug messages are not user facing -- if you're depending on them you should seek an alternative

**Comment by fwinkl** [comment]
OK, so what alternative do you suggest for user facing additional information? Pretty much every tool has a --verbose option that allows the more advanced user (not developer) to figure out what is going on if there are problems. Are you suggesting I should just change the level from DEBUG to INFO?

**Comment by asottile** [comment]
if anything it would be added to `--bug-report`

**Pull request closed without merging**
